### ISSUE TITLE
Problems with SimpleTest

### ISSUE THREAD

**Issue by kovtunos** [dockerizedrupal/docker-apache-2.4#17]
Don't know exactly where to post this issue. Today I tried to run some simpletests and Drupal reported about failed ones:

`GET <some-url> returned 0 (0 bytes)`

I also inserted into settings.php
`$conf['drupal_http_request_fails'] = FALSE;`

And pointed my development url directly:
`$base_url = 'mysite.dev';`

But all for nothing.
Vagrant passed same tests successfully. Therefore I think it's something about docker settings.

**Comment by viljaste** [comment]
My first thought about this is that if you run the tests inside the PHP container, then the URL that vhost is generating for your project is not resolvable inside the container.

What you could try is to add the extra_hosts directive for PHP container in the docker-compose.yml file like so:

```
php:
  extends:
    file: host.yml
    service: php
  image: dockerizedrupal/php-5.3:1.2.5
  hostname: php
  volumes:
    - ~/.ssh:/home/container/.ssh
  volumes_from:
    - apache-data
  links:
    - mysql
    - mailcatcher:smtp
    - memcached
  environment:
    - DRUPAL_VERSION=7
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=php
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-php-5.3/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/php-5.3:1.2.5
  extra_hosts:
    - "my-project.dev:192.18.11.89"
```

Replace the hostname my-project.dev with your project hostname and the IP address 192.18.11.89 with your real host's IP address.

And restart the project containers:

docker-compose kill
docker-compose up -d

I will look into it more closely, how to make it more manageable, since the solution above is not very ideal if this even was the case why running tests are not working for you.
